### PR TITLE
update and improve (?) readme

### PR DESCRIPTION
**Pull request by ealmdahl**
I think we should avoid specifying using a grid or list to present the recipes. We should allow the applicant to be creative.

Also, update links to reflect the new separated hyper-recipes repo.

### CODE REVIEW

**Comment by sindrenm** [comment]
I like this. :+1:

**Comment by jgorset** [comment]
I agree with this, too!

**Comment by jgorset** [comment]
Maybe something for you to consider, too, @zenangst and @NSElvis?

**Comment by zenangst** [comment]
I agree, there are more exciting ways to display content.

**Pull request merged**
